name: omop-learn
channels:
- conda-forge
- defaults
- pytorch
dependencies:
- jinja2==3.0.3
- numpy==1.20.3
- pandas==1.3.4
- pip==20.2.4
- pyspark[sql]==3.2.1
- python==3.8.5
- pytorch==1.7.1
- scikit-learn==1.0.1
- scipy==1.7.3
- sparse==0.13.0
- SQLAlchemy==1.4.27
- tqdm==4.62.3
- pip:
  - datasets==1.18.3
  - matplotlib==3.5.0
  - psycopg2==2.9.3
  - python-dotenv==0.20.0
  - sqlalchemy-bigquery==1.4.3
  - transformers==4.17.0
